In [2]:
from enum import Enum
import sys, os
import nasdaqdatalink
import pandas as pd 
import numpy as np
from scipy.stats.mstats import gmean
from sqlalchemy import create_engine

proj_root = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(''))), 'pynance')
print(proj_root)
sys.path.append(proj_root)

import nasdaq_data_link as nasdaq
from nasdaq_data_link import Sharadar
from numeric import custom_formatting

from calendar_dates import Calendar
from lib.equity.fundamentals import Fundamentals, Columns
from nasdaq_data_link import Nasdaq
cal = Calendar()

import warnings
warnings.filterwarnings('ignore')

pd.options.display.float_format = '{:,.4f}'.format


from sqlalchemy import create_engine
engine = create_engine('sqlite:///C:\data\industry_fundamentals.db', echo=False)
cnxn = engine.connect()

C:\dev\pynance
C:\dev\pynance\lib

In [5]:
# Get prices by ticker for index start date with shares outstanding and sector/industry
ndq = nasdaq.Nasdaq()


prev_bd = cal.previous_market_day(cal.today()).strftime('%Y-%m-%d')

prices = nasdaqdatalink.get_table(Sharadar.PRICES.value, date = '2022-01-03', paginate=True) 


tick = nasdaq.Tickers()
df_prof = tick.full_export(curl = False) # Set curl = True if data should be refreshed

df = prices.set_index('ticker') \
    .merge(df_prof.set_index('ticker'), how='inner', left_index=True, right_index=True).reset_index()

df = df[['ticker','date','open','closeadj','sector','industry']]
df

,ticker,date,open,closeadj,sector,industry
0,ZYXI,2022-01-03,9.2000,9.2550,Healthcare,Medical Devices
1,ZYNE,2022-01-03,2.9000,3.0200,Healthcare,Drug Manufacturers - Specialty & Generic
2,ZYME,2022-01-03,16.4900,16.9800,Healthcare,Biotechnology
3,ZY,2022-01-03,6.6900,7.0200,Basic Materials,Chemicals
4,ZWS,2022-01-03,36.6400,36.1060,Industrials,Specialty Industrial Machinery
...,...,...,...,...,...,...
5763,AADI,2022-01-03,24.4600,24.9700,Healthcare,Biotechnology
5764,AACI,2022-01-03,9.8100,9.9100,Industrials,Shell Companies
5765,AAC,2022-01-03,9.7500,9.7600,Industrials,Shell Companies
5766,AA,2022-01-03,60.2400,59.9130,Basic Materials,Aluminum
5767,A,2022-01-03,159.0000,155.7030,Healthcare,Diagnostics & Research