In [37]:
from enum import Enum
import sys, os
import nasdaqdatalink
import pandas as pd 
import numpy as np
from scipy.stats.mstats import gmean

proj_root = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(''))), 'pynance')
print(proj_root)
sys.path.append(proj_root)


import nasdaq_data_link as nasdaq
from nasdaq_data_link import Sharadar
from numeric import custom_formatting

from calendar_dates import Calendar
from lib.equity.fundamentals import Fundamentals, Columns
cal = Calendar()


import warnings
warnings.filterwarnings('ignore')

C:\dev\pynance


Two tables: One flat; One tall<br><br>
    CompFunBase - Company Fundamentals with a record indexed by Ticker and Calendar Date<br><br>
    CompFunRanks - Tall table indexed by Ticker, Industry, and Calendar Date with the companies ranks against their peer group (industry) <br>   Use this melted form to pivot and present ranks as a time series<br>
<br>
CompFunIndStats - descriptive statistics at the industry level for each date and metric
<br><br>
https://data.nasdaq.com/api/v3/datatables/SHARADAR/SF1?qopts.export=true&api_key=API_KEY

# Join equity fundamentals and static company info

In [2]:
# Fundamentals
fun = Fundamentals()
df_fun = fun.full_export(curl = False) # Set curl = True if data should be refreshed
df_fun = df_fun[df_fun.dimension == 'MRQ']

# Static Profile info
nasdaq.Nasdaq()
tick = nasdaq.Tickers()
df_prof = tick.full_export(curl = False) # Set curl = True if data should be refreshed

#Industry list
all_industies = df_prof.industry.unique().tolist()
# print(all_industies)

# Join
df = df_fun.set_index('ticker').merge(df_prof.set_index('ticker'), how='inner', left_index=True, right_index=True).reset_index()
df

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated_x,accoci,assets,assetsavg,assetsc,...,expgrowthrate,name,exchange,sector,industry,scalemarketcap,scalerevenue,famasector,famaindustry,lastupdated_y
0,A,MRQ,2017-03-31,2017-04-30,2017-04-30,2022-09-01,-477000000.0,8.016000e+09,NaN,3.800000e+09,...,-0.003245,AGILENT TECHNOLOGIES INC,NYSE,Healthcare,Diagnostics & Research,5 - Large,5 - Large,NaN,Measuring and Control Equipment,2022-09-01
1,A,MRQ,2017-06-30,2017-07-31,2017-07-31,2022-09-01,-417000000.0,8.261000e+09,NaN,3.996000e+09,...,-0.001922,AGILENT TECHNOLOGIES INC,NYSE,Healthcare,Diagnostics & Research,5 - Large,5 - Large,NaN,Measuring and Control Equipment,2022-09-01
2,A,MRQ,2017-09-30,2017-10-31,2017-10-31,2022-09-01,-346000000.0,8.426000e+09,NaN,4.169000e+09,...,-0.000939,AGILENT TECHNOLOGIES INC,NYSE,Healthcare,Diagnostics & Research,5 - Large,5 - Large,NaN,Measuring and Control Equipment,2022-09-01
3,A,MRQ,2017-12-31,2018-01-31,2018-01-31,2022-09-01,-269000000.0,8.698000e+09,NaN,4.397000e+09,...,0.002449,AGILENT TECHNOLOGIES INC,NYSE,Healthcare,Diagnostics & Research,5 - Large,5 - Large,NaN,Measuring and Control Equipment,2022-09-01
4,A,MRQ,2018-03-31,2018-04-30,2018-04-30,2022-09-01,-310000000.0,8.784000e+09,NaN,4.525000e+09,...,-0.002801,AGILENT TECHNOLOGIES INC,NYSE,Healthcare,Diagnostics & Research,5 - Large,5 - Large,NaN,Measuring and Control Equipment,2022-09-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123375,ZYXI,MRQ,2022-03-31,2022-03-31,2022-03-31,2022-07-29,0.0,1.320410e+08,NaN,8.217600e+07,...,0.003187,ZYNEX INC,NASDAQ,Healthcare,Medical Devices,3 - Small,2 - Micro,NaN,Medical Equipment,2022-07-29
123376,ZYXI,MRQ,2022-06-30,2022-06-30,2022-06-30,2022-07-29,0.0,1.195750e+08,NaN,7.063000e+07,...,0.006025,ZYNEX INC,NASDAQ,Healthcare,Medical Devices,3 - Small,2 - Micro,NaN,Medical Equipment,2022-07-29
123377,NaN,MRQ,2020-12-31,2020-12-31,2020-12-31,2022-08-12,0.0,6.149349e+07,NaN,5.900875e+07,...,NaN,NANO LABS LTD,NASDAQ,Technology,Semiconductors,3 - Small,1 - Nano,NaN,Electronic Equipment,2022-08-12
123378,NaN,MRQ,2021-12-31,2021-12-31,2021-12-31,2022-08-12,-2467327.0,9.098327e+08,NaN,8.934280e+08,...,NaN,NANO LABS LTD,NASDAQ,Technology,Semiconductors,3 - Small,1 - Nano,NaN,Electronic Equipment,2022-08-12
123379,NaN,MRQ,2022-06-30,2022-06-30,2022-06-30,2022-08-12,-1130435.0,8.061419e+08,NaN,7.435995e+08,...,NaN,NANO LABS LTD,NASDAQ,Technology,Semiconductors,3 - Small,1 - Nano,NaN,Electronic Equipment,2022-08-12

# Subset for rank columns of interest

In [3]:
df = df[Columns.RANKS.value]

In [4]:
cols = ['ticker', 'calendardate'] + [c for c in df.columns if c not in ['ticker', 'calendardate']]
df = df[cols]

In [5]:
df.shape

(123380, 59)

In [39]:
# df.columns.tolist()

# 1. load fundamentals to flat table

In [40]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///C:\data\industry_fundamentals.db', echo=False)
cnxn = engine.connect()
df.to_sql(con=cnxn, if_exists='replace', name = 'CompFunBase', index = False) #Company Fundamentals base

2022-10-22 21:58:15,305 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("CompFunBase")
2022-10-22 21:58:15,306 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:15,307 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("CompFunBase")
2022-10-22 21:58:15,308 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:15,309 INFO sqlalchemy.engine.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2022-10-22 21:58:15,310 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:15,312 INFO sqlalchemy.engine.Engine PRAGMA main.table_xinfo("CompFunBase")
2022-10-22 21:58:15,312 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:15,317 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2022-10-22 21:58:15,317 INFO sqlalchemy.engine.Engine [raw sql] ('CompFunBase',)
2022-10-22 21:58:15,317 INFO sqlalchemy.engine.Engine PRAGMA main.foreign_key_list("CompFunBase")
2022-10-22 21:58:15,319 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:15,319 INFO sqlalchemy.engine.Engine PRAGMA temp.foreign_key_list("CompFunBase")
2022-10-22 21:58:15,320 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:15,321 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2022-10-22 21:58:15,322 INFO sqlalchemy.engine.Engine [raw sql] ('CompFunBase',)
2022-10-22 21:58:15,323 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("CompFunBase")
2022-10-22 21:58:15,323 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:15,325 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("CompFunBase")
2022-10-22 21:58:15,326 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:15,327 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("CompFunBase")
2022-10-22 21:58:15,328 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:15,329 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("CompFunBase")
2022-10-22 21:58:15,329 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:15,330 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2022-10-22 21:58:15,331 INFO sqlalchemy.engine.Engine [raw sql] ('CompFunBase',)
2022-10-22 21:58:15,333 INFO sqlalchemy.engine.Engine
DROP TABLE "CompFunBase"
2022-10-22 21:58:15,334 INFO sqlalchemy.engine.Engine [no key 0.00065s] ()
2022-10-22 21:58:15,402 INFO sqlalchemy.engine.Engine COMMIT
2022-10-22 21:58:15,406 INFO sqlalchemy.engine.Engine
CREATE TABLE "CompFunBase" (
	ticker TEXT,
	calendardate TEXT,
	roc FLOAT,
	ebt FLOAT,
	roe FLOAT,
	famasector FLOAT,
	capex FLOAT,
	roa FLOAT,
	roic FLOAT,
	ncfo FLOAT,
	expebitgrow FLOAT,
	ncfx FLOAT,
	sgna FLOAT,
	ebitda FLOAT,
	industry TEXT,
	fcf FLOAT,
	ncfdiv FLOAT,
	sector TEXT,
	ncfcommon FLOAT,
	retearn FLOAT,
	ebit FLOAT,
	pe FLOAT,
	divyield FLOAT,
	ncfinv FLOAT,
	name TEXT,
	evebitda FLOAT,
	revenue FLOAT,
	grossmargin FLOAT,
	rnd FLOAT,
	netinc FLOAT,
	expnetincgrow FLOAT,
	de FLOAT,
	ncfdebt FLOAT,
	intcov FLOAT,
	opinc FLOAT,
	ros FLOAT,
	retentionratio FLOAT,
	gp FLOAT,
	oppmargin FLOAT,
	eqreinvestrate FLOAT,
	taxrate FLOAT,
	ncff FLOAT,
	eps FLOAT,
	expgrowthrate FLOAT,
	netmargin FLOAT,
	depamor FLOAT,
	famaindustry TEXT,
	fcfmargin FLOAT,
	ncf FLOAT,
	ncfi FLOAT,
	scalemarketcap TEXT,
	fcfps FLOAT,
	ncfbus FLOAT,
	cogs FLOAT,
	scalerevenue TEXT,
	pb FLOAT,
	exproegrow FLOAT,
	"p/cf" FLOAT,
	opex FLOAT
)


2022-10-22 21:58:15,407 INFO sqlalchemy.engine.Engine [no key 0.00062s] ()
2022-10-22 21:58:15,465 INFO sqlalchemy.engine.Engine COMMIT
2022-10-22 21:58:20,628 INFO sqlalchemy.engine.Engine INSERT INTO "CompFunBase" (ticker, calendardate, roc, ebt, roe, famasector, capex, roa, roic, ncfo, expebitgrow, ncfx, sgna, ebitda, industry, fcf, ncfdiv, sector, ncfcommon, retearn, ebit, pe, divyield, ncfinv, name, evebitda, revenue, grossmargin, rnd, netinc, expnetincgrow, de, ncfdebt, intcov, opinc, ros, retentionratio, gp, oppmargin, eqreinvestrate, taxrate, ncff, eps, expgrowthrate, netmargin, depamor, famaindustry, fcfmargin, ncf, ncfi, scalemarketcap, fcfps, ncfbus, cogs, scalerevenue, pb, exproegrow, "p/cf", opex) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2022-10-22 21:58:20,629 INFO sqlalchemy.engine.Engine [generated in 4.20443s] (('A', '2017-03-31', 0.025565081839438817, 191000000.0, 0.03751143641354071, None, -43000000.0, None, None, 257000000.0, -0.000612626656274357, 1000000.0, 307000000.0, 265000000.0, 'Diagnostics & Research', 214000000.0, -43000000.0, 'Healthcare', -75000000.0, -393000000.0, 211000000.0, 30.486, 0.009, 0.0, 'AGILENT TECHNOLOGIES INC', 18.035, 1102000000.0, 0.537, 84000000.0, 164000000.0, -0.0008989021043000915, 0.833, 52000000.0, 10.55, 201000000.0, None, -0.023963414634146342, 592000000.0, 0.1823956442831216, -0.023963414634146342, 0.14136125654450263, -67000000.0, 0.51, -0.0032448173521076474, 0.5372050816696915, 54000000.0, 'Measuring and Control Equipment', 0.19419237749546278, 48000000.0, -43000000.0, '5 - Large', 0.667, 0.0, 510000000.0, '5 - Large', 4.058, 0.004649606411674209, 82.90964869158879, 391000000.0), ('A', '2017-06-30', 0.02616235610704141, 193000000.0, 0.03797743055555555, None, -43000000.0, None, None, 228000000.0, -0.00038869786216175813, 18000000.0, 308000000.0, 263000000.0, 'Diagnostics & Research', 185000000.0, -42000000.0, 'Healthcare', 32000000.0, -260000000.0, 212000000.0, 30.352, 0.009, -1000000.0, 'AGILENT TECHNOLOGIES INC', 18.461, 1114000000.0, 0.535, 87000000.0, 175000000.0, -0.0005642361111111111, 0.792, 39000000.0, 11.157894736842104, 201000000.0, None, -0.014857142857142857, 596000000.0, 0.18043087971274685, -0.014857142857142857, 0.09326424870466321, 29000000.0, 0.55, -0.0019216269841269842, 0.5350089766606823, 51000000.0, 'Measuring and Control Equipment', 0.16606822262118492, 0.0, -101000000.0, '5 - Large', 0.576, -57000000.0, 518000000.0, '5 - Large', 4.169, 0.0029559008409909705, 103.85278765945947, 395000000.0), ('A', '2017-09-30', 0.025869628763519437, 226000000.0, 0.03663837714758849, None, -58000000.0, None, None, 288000000.0, -0.0001841566793335282, -6000000.0, 347000000.0, 298000000.0, 'Diagnostics & Research', 230000000.0, -43000000.0, 'Healthcare', 8000000.0, -126000000.0, 246000000.0, 32.009, 0.008, -1000000.0, 'AGILENT TECHNOLOGIES INC', 19.572, 1189000000.0, 0.536, 91000000.0, 177000000.0, -0.0002608155661353757, 0.743, -70000000.0, 12.3, 199000000.0, None, -0.00711864406779661, 637000000.0, 0.16736753574432295, -0.00711864406779661, 0.2168141592920354, -106000000.0, 0.55, -0.0009386413312329622, 0.535744322960471, 52000000.0, 'Measuring and Control Equipment', 0.1934398654331371, 391000000.0, -59000000.0, '5 - Large', 0.714, 0.0, 552000000.0, '5 - Large', 4.532, 0.007795422856743746, 95.19112627826087, 438000000.0), ('A', '2017-12-31', -0.047997600119994, 233000000.0, -0.07076514816452897, None, -60000000.0, None, None, 215000000.0, -0.0007934603269836509, 25000000.0, 347000000.0, 304000000.0, 'Diagnostics & Research', 155000000.0, -48000000.0, 'Healthcare', -22000000.0, -529000000.0, 253000000.0, 121.016, 0.007, -1000000.0, 'AGILENT TECHNOLOGIES INC', 20.4, 1211000000.0, 0.553, 94000000.0, -320000000.0, -0.0011698363555948696, 0.923, 135000000.0, 12.65, 229000000.0, None, 0.01653125, 670000000.0, 0.18909991742361684, 0.01653125, 2.3733905579399144, 37000000.0, -0.99, 0.002449344869526758, 0.5532617671345995, 51000000.0, 'Measuring and Control Equipment', 0.12799339388934763, 210000000.0, -67000000.0, '5 - Large', 0.48, -6000000.0, 541000000.0, '5 - Large', 5.245, 0.09006566839040023, 153.0271853096774, 441000000.0), ('A', '2018-03-31', 0.030469678953626636, 227000000.0, 0.04443962714068936, None, -48000000.0, None, None, 303000000.0, -0.0006123662306777646, -16000000.0, 341000000.0, 296000000.0, 'Diagnostics & Research', 255000000.0, -48000000.0, 'Healthcare', -35000000.0, -412000000.0, 246000000.0, 89.45, 0.009, -2000000.0, 'AGILENT TECHNOLOGIES INC', 17.621, 1206000000.0, 0.533, 92000000.0, 205000000.0, -0.0008931281161933666, 0.903, -30000000.0, 12.947368421052632, 210000000.0, None, -0.020097560975609757, 643000000.0, 0.17412935323383086, -0.020097560975609757, 0.09691629955947137, -114000000.0, 0.64, -0.0028013725790845597, 0.533167495854063, 50000000.0, 'Measuring and Control Equipment', 0.21144278606965175, 122000000.0, -51000000.0, '5 - Large', 0.792, -1000000.0, 563000000.0, '5 - Large', 4.596, 0.003543610239540719, 83.13572667843137, 433000000.0), ('A', '2018-06-30', 0.03708942322803709, 242000000.0, 0.051709027169149865, None, -33000000.0, None, None, 197000000.0, -0.0006537796636806538, -14000000.0, 341000000.0, 313000000.0, 'Diagnostics & Research', 164000000.0, -48000000.0, 'Healthcare', -226000000.0, -416000000.0, 260000000.0, 70.905, 0.009, -10000000.0, 'AGILENT TECHNOLOGIES INC', 16.708, 1203000000.0, 0.548, 97000000.0, 236000000.0, -0.0009114811568799298, 0.828, -315000000.0, 14.444444444444445, 221000000.0, None, -0.017627118644067796, 659000000.0, 0.18370739817123857, -0.017627118644067796, 0.024793388429752067, -589000000.0, 0.74, -0.002545195264338448, 0.5477971737323358, 53000000.0, 'Measuring and Control Equipment', 0.13632585203657524, -879000000.0, -473000000.0, '5 - Large', 0.512, -430000000.0, 544000000.0, '5 - Large', 4.63, 0.0010130883218191949, 128.83925854268293, 438000000.0), ('A', '2018-09-30', 0.030631479736098022, 244000000.0, 0.04269761331289687, None, -35000000.0, None, None, 372000000.0, -0.000527803958529689, -12000000.0, 360000000.0, 318000000.0, 'Diagnostics & Research', 337000000.0, -47000000.0, 'Healthcare', -83000000.0, -336000000.0, 262000000.0, 65.358, 0.009, 0.0, 'AGILENT TECHNOLOGIES INC', 16.508, 1294000000.0, 0.547, 104000000.0, 195000000.0, -0.000735712721699146, 0.869, 0.0, 14.555555555555555, 244000000.0, None, -0.01723076923076923, 708000000.0, 0.18856259659969088, -0.01723076923076923, 0.20081967213114754, -131000000.0, 0.6, -0.0026712031126307455, 0.5471406491499228, 56000000.0, 'Measuring and Control Equipment', 0.2604327666151468, 115000000.0, -114000000.0, '5 - Large', 1.06, -79000000.0, 586000000.0, '5 - Large', 4.522, 0.00826496294350623, 61.28510074183976, 464000000.0), ('A', '2018-12-31', 0.07374890254609306, 248000000.0, 0.10007942811755362, None, -39000000.0, None, None, 213000000.0, 0.00013169446883230904, 9000000.0, 355000000.0, 320000000.0, 'Diagnostics & Research', 174000000.0, -52000000.0, 'Healthcare', -53000000.0, 90000000.0, 266000000.0, 21.25, 0.008, -3000000.0, 'AGILENT TECHNOLOGIES INC', 19.067, 1284000000.0, 0.551, 102000000.0, 504000000.0, 0.00017871326449563145, 0.778, 0.0, 14.777777777777779, 250000000.0, None, 0.0017857142857142857, 707000000.0, 0.19470404984423675, 0.0017857142857142857, -1.032258064516129, -122000000.0, 1.58, 0.0002506949960285941, 0.5506230529595015, 54000000.0, 'Measuring and Control Equipment', 0.13551401869158877, -190000000.0, -290000000.0, '5 - Large', 0.547, -248000000.0, 577000000.0, '5 - Large', 4.81, -0.04017861357349872, 139.2209123965517, 457000000.0)  ... displaying 10 of 123380 total bound parameter sets ...  (None, '2021-12-31', None, None, None, None, None, None, None, None, None, None, None, None, 'Semiconductors', None, None, 'Technology', None, -223679698.0, None, None, None, None, 'NANO LABS LTD', None, None, None, None, None, None, -37.893, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'Electronic Equipment', None, None, None, '3 - Small', None, None, None, '1 - Nano', None, None, None, None), (None, '2022-06-30', None, None, None, None, None, None, None, None, None, None, None, None, 'Semiconductors', None, None, 'Technology', None, -112286174.0, None, None, None, None, 'NANO LABS LTD', None, None, None, None, None, None, 7.692, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'Electronic Equipment', None, None, None, '3 - Small', None, None, None, '1 - Nano', None, None, None, None))

2022-10-22 21:58:22,224 INFO sqlalchemy.engine.Engine COMMIT
2022-10-22 21:58:22,925 INFO sqlalchemy.engine.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2022-10-22 21:58:22,925 INFO sqlalchemy.engine.Engine [raw sql] ()

123380

In [41]:
base = pd.read_sql("select * from CompFunBase where industry = 'Utilities - Regulated Electric' and ticker = 'DUK'", cnxn)
base

2022-10-22 21:58:22,944 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("select * from CompFunBase where industry = 'Utilities - Regulated Electric' and ticker = 'DUK'")
2022-10-22 21:58:22,945 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:22,947 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("select * from CompFunBase where industry = 'Utilities - Regulated Electric' and ticker = 'DUK'")
2022-10-22 21:58:22,947 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 21:58:22,949 INFO sqlalchemy.engine.Engine select * from CompFunBase where industry = 'Utilities - Regulated Electric' and ticker = 'DUK'
2022-10-22 21:58:22,950 INFO sqlalchemy.engine.Engine [raw sql] ()

,ticker,calendardate,roc,ebt,roe,famasector,capex,roa,roic,ncfo,...,ncfi,scalemarketcap,fcfps,ncfbus,cogs,scalerevenue,pb,exproegrow,p/cf,opex
0,DUK,2017-03-31,0.007639,1.060000e+09,0.017388,None,-2.160000e+09,None,None,1.246000e+09,...,-2.361000e+09,5 - Large,-1.306,0.0,3.479000e+09,5 - Large,1.393,0.005370,-62.773355,8.480000e+08
1,DUK,2017-06-30,0.007276,1.013000e+09,0.016617,None,-1.771000e+09,None,None,1.554000e+09,...,-1.983000e+09,5 - Large,-0.310,0.0,3.365000e+09,5 - Large,1.417,0.005132,-269.600295,8.280000e+08
2,DUK,2017-09-30,0.010048,1.318000e+09,0.022916,None,-1.910000e+09,None,None,2.178000e+09,...,-1.987000e+09,5 - Large,0.383,0.0,3.720000e+09,5 - Large,1.411,0.005282,219.178493,8.940000e+08
3,DUK,2017-12-31,0.007309,8.640000e+08,0.016843,None,-2.211000e+09,None,None,1.646000e+09,...,-2.111000e+09,5 - Large,-0.807,0.0,3.595000e+09,5 - Large,1.411,0.002664,-104.203449,9.290000e+08
4,DUK,2018-03-31,0.006343,8.010000e+08,0.014835,None,-2.087000e+09,None,None,1.391000e+09,...,-2.264000e+09,5 - Large,-0.993,0.0,3.769000e+09,5 - Large,1.298,0.003042,-77.925544,1.067000e+09
5,DUK,2018-06-30,0.005074,6.000000e+08,0.011763,None,-2.288000e+09,None,None,1.911000e+09,...,-2.381000e+09,5 - Large,-0.536,0.0,3.522000e+09,5 - Large,1.304,0.001891,-147.044177,9.700000e+08
6,DUK,2018-09-30,0.010836,1.250000e+09,0.025166,None,-2.377000e+09,None,None,2.365000e+09,...,-2.625000e+09,5 - Large,-0.017,0.0,3.896000e+09,5 - Large,1.326,0.002378,-4750.218751,1.029000e+09
7,DUK,2018-12-31,0.004560,4.630000e+08,0.010589,None,-2.637000e+09,None,None,1.519000e+09,...,-2.790000e+09,5 - Large,-1.559,0.0,4.084000e+09,5 - Large,1.404,-0.000021,-55.028026,1.097000e+09
8,DUK,2019-03-31,0.008512,9.950000e+08,0.019987,None,-2.536000e+09,None,None,1.239000e+09,...,-2.713000e+09,5 - Large,-1.784,0.0,3.698000e+09,5 - Large,1.453,0.001389,-50.447941,1.092000e+09
9,DUK,2019-06-30,0.007736,9.730000e+08,0.018402,None,-2.929000e+09,None,None,1.817000e+09,...,-3.075000e+09,5 - Large,-1.527,0.0,3.485000e+09,5 - Large,1.421,0.002041,-57.772359,1.086000e+09
10,DUK,2019-09-30,0.012394,1.530000e+09,0.028899,None,-2.619000e+09,None,None,2.581000e+09,...,-2.845000e+09,5 - Large,-0.052,0.0,3.845000e+09,5 - Large,1.504,0.002385,-1837.992042,1.186000e+09
11,DUK,2019-12-31,0.006154,7.690000e+08,0.014395,None,-3.038000e+09,None,None,2.572000e+09,...,-3.324000e+09,5 - Large,-0.637,0.0,3.798000e+09,5 - Large,1.420,0.001484,-142.693322,1.180000e+09
12,DUK,2020-03-31,0.008319,1.075000e+09,0.019991,None,-2.832000e+09,None,None,1.554000e+09,...,-3.022000e+09,5 - Large,-1.741,0.0,3.330000e+09,5 - Large,1.264,0.001838,-46.409296,1.131000e+09
13,DUK,2020-06-30,-0.007190,-1.118000e+09,-0.017633,None,-2.271000e+09,None,None,1.803000e+09,...,-2.449000e+09,5 - Large,-0.637,0.0,3.095000e+09,5 - Large,1.291,-0.001429,-125.443097,1.149000e+09
14,DUK,2020-09-30,0.011692,1.409000e+09,0.028344,None,-2.305000e+09,None,None,3.409000e+09,...,-2.493000e+09,5 - Large,1.502,0.0,3.664000e+09,5 - Large,1.416,0.001290,58.994448,1.243000e+09
15,DUK,2020-12-31,-0.000562,-2.250000e+08,-0.001313,None,-2.499000e+09,None,None,2.090000e+09,...,-2.640000e+09,5 - Large,-0.550,0.0,3.547000e+09,5 - Large,1.405,0.001992,-164.753950,2.156000e+09
16,DUK,2021-03-31,0.008705,1.076000e+09,0.020587,None,-2.215000e+09,None,None,2.088000e+09,...,-3.137000e+09,5 - Large,-0.165,0.0,3.474000e+09,5 - Large,1.540,0.001104,-584.244845,1.226000e+09
17,DUK,2021-06-30,0.006645,8.010000e+08,0.015894,None,-2.421000e+09,None,None,1.785000e+09,...,-2.477000e+09,5 - Large,-0.827,0.0,3.253000e+09,5 - Large,1.578,0.000536,-119.398263,1.336000e+09
18,DUK,2021-09-30,0.012186,1.495000e+09,0.028495,None,-2.453000e+09,None,None,3.354000e+09,...,-2.586000e+09,5 - Large,1.172,0.0,3.797000e+09,5 - Large,1.523,0.001084,83.329252,1.467000e+09
19,DUK,2021-12-31,0.006348,7.280000e+08,0.015133,None,-2.626000e+09,None,None,1.063000e+09,...,-2.735000e+09,5 - Large,-2.033,0.0,3.867000e+09,5 - Large,1.637,-0.000278,-51.634114,1.304000e+09
20,DUK,2022-03-31,0.007150,8.430000e+08,0.017332,None,-2.551000e+09,None,None,1.795000e+09,...,-2.699000e+09,5 - Large,-0.982,0.0,4.320000e+09,5 - Large,1.737,-0.000198,-113.633006,1.533000e+09
21,DUK,2022-06-30,0.007499,9.840000e+08,0.018242,None,-2.566000e+09,None,None,2.240000e+09,...,-2.793000e+09,5 - Large,-0.423,0.0,3.987000e+09,5 - Large,1.660,0.001029,-253.193346,1.285000e+09

# 2. load ranks to tall table

CompFunRanks

In [6]:
dates = df['calendardate'].unique().tolist()
industries =  df['industry'].unique().tolist()

In [8]:
frames =[]
for date in dates[-6:]:
    for industry in industries:
        data = df[(df.calendardate == date) & (df.industry == industry)].set_index(['ticker','calendardate','industry'])
        ranks = data.rank(axis=1, pct=True, numeric_only = True).reset_index()
        melt = ranks.melt(id_vars = ['ticker', 'calendardate','industry'])
        frames.append(melt)
res = pd.concat(frames, axis=0)

In [9]:
res

   ticker calendardate                 industry     variable     value
0       A   2021-09-30   Diagnostics & Research         cogs  0.957447
1     AKU   2021-09-30   Diagnostics & Research         cogs  0.936170
2    ANIX   2021-09-30   Diagnostics & Research         cogs  0.579545
3     AWH   2021-09-30   Diagnostics & Research         cogs  0.914894
4    AXDX   2021-09-30   Diagnostics & Research         cogs  0.872340
..    ...          ...                      ...          ...       ...
46    JEF   2022-09-30  Financial Conglomerates          ebt  0.765957
47    JEF   2022-09-30  Financial Conglomerates  expebitgrow  0.191489
48    JEF   2022-09-30  Financial Conglomerates    netmargin  0.468085
49    JEF   2022-09-30  Financial Conglomerates         ncfx  0.148936
50    JEF   2022-09-30  Financial Conglomerates   exproegrow  0.212766

[1245930 rows x 5 columns]

In [15]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///C:\data\industry_fundamentals.db', echo=False)
cnxn = engine.connect()
res.to_sql(con=cnxn, if_exists='replace', name = 'CompFunRanks', index = False) #Company Fundamentals Ranks

2022-10-22 22:34:46,561 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("CompFunRanks")
2022-10-22 22:34:46,562 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:34:46,563 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("CompFunRanks")
2022-10-22 22:34:46,564 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:34:46,565 INFO sqlalchemy.engine.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2022-10-22 22:34:46,566 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:34:46,568 INFO sqlalchemy.engine.Engine PRAGMA main.table_xinfo("CompFunRanks")
2022-10-22 22:34:46,569 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:34:46,574 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2022-10-22 22:34:46,575 INFO sqlalchemy.engine.Engine [raw sql] ('CompFunRanks',)
2022-10-22 22:34:46,577 INFO sqlalchemy.engine.Engine PRAGMA main.foreign_key_list("CompFunRanks")
2022-10-22 22:34:46,577 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:34:46,579 INFO sqlalchemy.engine.Engine PRAGMA temp.foreign_key_list("CompFunRanks")
2022-10-22 22:34:46,580 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:34:46,580 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2022-10-22 22:34:46,581 INFO sqlalchemy.engine.Engine [raw sql] ('CompFunRanks',)
2022-10-22 22:34:46,584 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("CompFunRanks")
2022-10-22 22:34:46,584 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:34:46,585 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("CompFunRanks")
2022-10-22 22:34:46,586 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:34:46,587 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("CompFunRanks")
2022-10-22 22:34:46,587 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:34:46,588 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("CompFunRanks")
2022-10-22 22:34:46,589 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:34:46,590 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2022-10-22 22:34:46,590 INFO sqlalchemy.engine.Engine [raw sql] ('CompFunRanks',)
2022-10-22 22:34:46,594 INFO sqlalchemy.engine.Engine
DROP TABLE "CompFunRanks"
2022-10-22 22:34:46,595 INFO sqlalchemy.engine.Engine [no key 0.00072s] ()
2022-10-22 22:34:46,690 INFO sqlalchemy.engine.Engine COMMIT
2022-10-22 22:34:46,691 INFO sqlalchemy.engine.Engine
CREATE TABLE "CompFunRanks" (
	ticker TEXT,
	calendardate TEXT,
	industry TEXT,
	variable TEXT,
	value FLOAT
)


2022-10-22 22:34:46,692 INFO sqlalchemy.engine.Engine [no key 0.00055s] ()
2022-10-22 22:34:46,753 INFO sqlalchemy.engine.Engine COMMIT
2022-10-22 22:34:52,300 INFO sqlalchemy.engine.Engine INSERT INTO "CompFunRanks" (ticker, calendardate, industry, variable, value) VALUES (?, ?, ?, ?, ?)
2022-10-22 22:34:52,301 INFO sqlalchemy.engine.Engine [generated in 4.55126s] (('A', '2021-09-30', 'Diagnostics & Research', 'cogs', 0.9574468085106383), ('AKU', '2021-09-30', 'Diagnostics & Research', 'cogs', 0.9361702127659575), ('ANIX', '2021-09-30', 'Diagnostics & Research', 'cogs', 0.5795454545454546), ('AWH', '2021-09-30', 'Diagnostics & Research', 'cogs', 0.9148936170212766), ('AXDX', '2021-09-30', 'Diagnostics & Research', 'cogs', 0.8723404255319149), ('BDSX', '2021-09-30', 'Diagnostics & Research', 'cogs', 0.8936170212765957), ('BIOC', '2021-09-30', 'Diagnostics & Research', 'cogs', 0.9787234042553191), ('BMRA', '2021-09-30', 'Diagnostics & Research', 'cogs', 0.9787234042553191)  ... displaying 10 of 1245930 total bound parameter sets ...  ('JEF', '2022-09-30', 'Financial Conglomerates', 'ncfx', 0.14893617021276595), ('JEF', '2022-09-30', 'Financial Conglomerates', 'exproegrow', 0.2127659574468085))
2022-10-22 22:34:55,733 INFO sqlalchemy.engine.Engine COMMIT
2022-10-22 22:34:56,529 INFO sqlalchemy.engine.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2022-10-22 22:34:56,530 INFO sqlalchemy.engine.Engine [raw sql] ()

1245930

In [12]:
# res[(res.ticker == 'AMZN') & (res.variable == 'revenue')]

     ticker calendardate         industry variable  value
1703   AMZN   2021-09-30  Internet Retail  revenue    1.0
1888   AMZN   2021-12-31  Internet Retail  revenue    1.0
1740   AMZN   2022-03-31  Internet Retail  revenue    1.0
1740   AMZN   2022-06-30  Internet Retail  revenue    1.0

In [16]:
rank = pd.read_sql("select * from CompFunRanks where ticker == 'AMZN'", cnxn)
rank

2022-10-22 22:35:09,073 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("select * from CompFunRanks where ticker == 'AMZN'")
2022-10-22 22:35:09,075 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:35:09,076 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("select * from CompFunRanks where ticker == 'AMZN'")
2022-10-22 22:35:09,077 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-22 22:35:09,078 INFO sqlalchemy.engine.Engine select * from CompFunRanks where ticker == 'AMZN'
2022-10-22 22:35:09,079 INFO sqlalchemy.engine.Engine [raw sql] ()

    ticker calendardate         industry     variable     value
0     AMZN   2021-09-30  Internet Retail         cogs  0.957447
1     AMZN   2021-09-30  Internet Retail    ncfcommon  0.276596
2     AMZN   2021-09-30  Internet Retail      ncfdebt  0.117021
3     AMZN   2021-09-30  Internet Retail        fcfps  0.212766
4     AMZN   2021-09-30  Internet Retail         roic       NaN
..     ...          ...              ...          ...       ...
199   AMZN   2022-06-30  Internet Retail          ebt  0.106383
200   AMZN   2022-06-30  Internet Retail  expebitgrow  0.489362
201   AMZN   2022-06-30  Internet Retail    netmargin  0.595745
202   AMZN   2022-06-30  Internet Retail         ncfx  0.170213
203   AMZN   2022-06-30  Internet Retail   exproegrow  0.425532

[204 rows x 5 columns]

# 3. Industry descriptive stats

In [22]:
dates = df['calendardate'].unique().tolist()
industries =  df['industry'].unique().tolist()

In [36]:
frames =[]
for date in dates[-6:]:
    for industry in industries:
        data = df[(df.calendardate == date) & (df.industry == industry)].set_index(['ticker','calendardate','industry'])
        stats = data.describe().reset_index()
        stats.rename(columns={'index':'stat'}, inplace = True)
        stats['calendardate'] = date
        stats['industry'] = industry
        melt = stats.melt(id_vars = ['calendardate','industry','stat'])
        frames.append(melt)
res = pd.concat(frames, axis=0)

C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)

C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))

C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4488: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4489: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\sands\.conda\envs\pynance_venv\lib\site-packages\numpy\lib\function_base.py:4486: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

In [38]:
res

    calendardate                 industry   stat    variable         value
0     2021-06-30   Diagnostics & Research  count        cogs  9.400000e+01
1     2021-06-30   Diagnostics & Research   mean        cogs  2.311812e+08
2     2021-06-30   Diagnostics & Research    std        cogs  6.830261e+08
3     2021-06-30   Diagnostics & Research    min        cogs  0.000000e+00
4     2021-06-30   Diagnostics & Research    25%        cogs  1.631000e+06
..           ...                      ...    ...         ...           ...
403   2022-09-30  Financial Conglomerates    min  exproegrow  2.650678e-03
404   2022-09-30  Financial Conglomerates    25%  exproegrow  2.650678e-03
405   2022-09-30  Financial Conglomerates    50%  exproegrow  2.650678e-03
406   2022-09-30  Financial Conglomerates    75%  exproegrow  2.650678e-03
407   2022-09-30  Financial Conglomerates    max  exproegrow  2.650678e-03

[369648 rows x 5 columns]

In [39]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///C:\data\industry_fundamentals.db', echo=False)
cnxn = engine.connect()
res.to_sql(con=cnxn, if_exists='replace', name = 'CompFunIndStats', index = False) #Company Fundamentals Ranks

2022-10-23 00:44:50,208 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("CompFunIndStats")
2022-10-23 00:44:50,209 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-23 00:44:50,210 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("CompFunIndStats")
2022-10-23 00:44:50,211 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-23 00:44:50,215 INFO sqlalchemy.engine.Engine
CREATE TABLE "CompFunIndStats" (
	calendardate TEXT,
	industry TEXT,
	stat TEXT,
	variable TEXT,
	value FLOAT
)


2022-10-23 00:44:50,215 INFO sqlalchemy.engine.Engine [no key 0.00094s] ()
2022-10-23 00:44:50,221 INFO sqlalchemy.engine.Engine COMMIT
2022-10-23 00:44:52,297 INFO sqlalchemy.engine.Engine INSERT INTO "CompFunIndStats" (calendardate, industry, stat, variable, value) VALUES (?, ?, ?, ?, ?)
2022-10-23 00:44:52,298 INFO sqlalchemy.engine.Engine [generated in 1.65482s] (('2021-06-30', 'Diagnostics & Research', 'count', 'cogs', 94.0), ('2021-06-30', 'Diagnostics & Research', 'mean', 'cogs', 231181210.40425533), ('2021-06-30', 'Diagnostics & Research', 'std', 'cogs', 683026084.5048014), ('2021-06-30', 'Diagnostics & Research', 'min', 'cogs', 0.0), ('2021-06-30', 'Diagnostics & Research', '25%', 'cogs', 1631000.0), ('2021-06-30', 'Diagnostics & Research', '50%', 'cogs', 14908000.0), ('2021-06-30', 'Diagnostics & Research', '75%', 'cogs', 75173750.0), ('2021-06-30', 'Diagnostics & Research', 'max', 'cogs', 4749000000.0)  ... displaying 10 of 369648 total bound parameter sets ...  ('2022-09-30', 'Financial Conglomerates', '75%', 'exproegrow', 0.0026506778313094325), ('2022-09-30', 'Financial Conglomerates', 'max', 'exproegrow', 0.0026506778313094325))
2022-10-23 00:44:53,047 INFO sqlalchemy.engine.Engine COMMIT
2022-10-23 00:44:53,266 INFO sqlalchemy.engine.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2022-10-23 00:44:53,267 INFO sqlalchemy.engine.Engine [raw sql] ()

369648