In [ ]:
''' 5-,10-,30-,90- losers joined with Fundamentals Percentile Ranks; Price weighted performance of Equity Sectors (5-,10-,30-,90-, horizontal bar chart)
'''

In [1]:
from enum import Enum
import sys, os
import nasdaqdatalink
import pandas as pd 
import numpy as np
from scipy.stats.mstats import gmean
from sqlalchemy import create_engine

proj_root = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(''))), 'pynance')
print(proj_root)
sys.path.append(proj_root)

import nasdaq_data_link as nasdaq
from nasdaq_data_link import Sharadar
from numeric import custom_formatting

from calendar_dates import Calendar
from lib.equity.fundamentals import Fundamentals, Columns
cal = Calendar()

import warnings
warnings.filterwarnings('ignore')

C:\dev\pynance
C:\dev\pynance\lib

In [4]:
ndq = nasdaq.Nasdaq()

In [5]:
data = nasdaqdatalink.get_table(Sharadar.PRICES.value, date = '2022-11-03', paginate=True) # All MRQ periods; One Ticker
data

,ticker,date,open,high,low,close,volume,closeadj,closeunadj,lastupdated
None,,,,,,,,,,
0,ZYXI,2022-11-03,12.300,12.310,11.550,12.080,310160.0,12.080,12.080,2022-11-03
1,ZYNE,2022-11-03,0.709,0.736,0.685,0.720,142912.0,0.720,0.720,2022-11-03
2,ZYME,2022-11-03,7.050,7.490,7.010,7.360,976845.0,7.360,7.360,2022-11-03
3,ZWS,2022-11-03,22.460,23.090,22.300,22.720,1498596.0,22.720,22.720,2022-11-03
4,ZWRKW,2022-11-03,0.005,0.005,0.005,0.005,41.0,0.005,0.005,2022-11-03
...,...,...,...,...,...,...,...,...,...,...
8037,AACI,2022-11-03,9.965,9.965,9.965,9.965,39.0,9.965,9.965,2022-11-03
8038,AACG,2022-11-03,1.800,1.900,1.700,1.770,29261.0,1.770,1.770,2022-11-03
8039,AAC,2022-11-03,9.970,9.978,9.960,9.970,31181.0,9.970,9.970,2022-11-03
8040,AA,2022-11-03,37.140,38.190,36.512,37.700,4407292.0,37.700,37.700,2022-11-03
8041,A,2022-11-03,133.770,135.865,130.660,134.460,1199449.0,134.460,134.460,2022-11-03