In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

from IPython.display import display_html
from itertools import chain,cycle
def display_side_by_side(*args,titles=cycle([''])):
    html_str=''
    for df,title in zip(args, chain(titles,cycle(['</br>'])) ):
        html_str+='<th style="text-align:center"><td style="vertical-align:top">'
        html_str+=df.to_html().replace('table','table style="display:inline-block"')
        html_str+='</td></th>'
    display_html(html_str,raw=True)

import warnings
warnings.filterwarnings('ignore')

In [2]:
from lib.equity.fundamentals import Fundamentals, Ranks, DCF, Columns

C:\dev\pynance\lib

In [3]:
ticker = ['JNJ'] # Can pass multiple tickers

In [4]:
rank = Ranks(ticker = ticker[0])
ranks = rank.get_ranks()

# Fundamentals

Left Frame: Values as reported (in Millions, USD)<br>
Middle Frame: Percent Change <br>
Right Frame: Percentile Rank vs. Industry Peers (Higher values are assigned lower percentile rank)<br>

In [5]:
fun = Fundamentals( ticker = ticker)
fun

In [6]:
x = fun.get( columns = Columns.INCOME.value, limit = 5 ).style_jupyter(fun.df)
y = fun.percent_change().style_jupyter(fun.pct_chg, units = '%')
r = ranks.iloc[:, ranks.columns.get_level_values(1).isin(Columns.INCOME.value)].round(2)

display_side_by_side(x, y, rank.print_ranks(r))

In [7]:
x = fun.get( columns = Columns.CASHFLOW.value, limit = 5 ).style_jupyter(fun.df)
y = fun.percent_change().style_jupyter(fun.pct_chg, units = '%')

r = ranks.iloc[:, ranks.columns.get_level_values(1).isin(Columns.CASHFLOW.value)].round(2)
display_side_by_side(x, y, rank.print_ranks(r))

In [8]:
x = fun.get( columns = Columns.BALANCE.value, limit = 5 ).style_jupyter(fun.df)
y = fun.percent_change().style_jupyter(fun.pct_chg, units = '%')

r = ranks.iloc[:, ranks.columns.get_level_values(1).isin(Columns.BALANCE.value)].round(2)
display_side_by_side(x, y, rank.print_ranks(r))

In [9]:
x = fun.get( columns = Columns.PEERS.value, limit = 5 ).style_jupyter(fun.df, units = '%')

r = ranks.iloc[:, ranks.columns.get_level_values(1).isin(Columns.PEERS.value)].round(2)
display_side_by_side(x, rank.print_ranks(r))

## Peers

In [10]:
peers = fun.get_peers()
fun = Fundamentals( ticker = peers)
print(fun)

x = fun.get( columns = Columns.INCOME.value, limit = 5 ).style_jupyter(fun.df)
y = fun.get( columns = Columns.PEERS.value, limit = 5 ).style_jupyter(fun.df, units = '%')
z = fun.get( columns = Columns.CASHFLOW_.value, limit = 5 ).style_jupyter(fun.df)

# y = fun.percent_change().style_jupyter(fun.pct_chg, units = '%')

display_side_by_side(x,y,z)

Drug Manufacturers - General
Fundamentals:Object:['JNJ', 'PFE', 'MRK', 'ABBV']

## DCF

In [11]:
fun = Fundamentals( ticker = ticker)
x = fun.get( columns = Columns.INCOME.value, limit = 8 ).percent_change().style_jupyter(fun.pct_chg, units='%')
y = fun.get( columns = Columns.INCOME.value, limit = 8).describe().style_jupyter(fun.desc, units = '%')
display_side_by_side(x, y)

Describe % Change:

## Base Case

In [12]:
dcf = DCF(ticker=ticker, REV_GROWTH=0.025)
dcf.forecast_as_percent_of_revenue(type = 'INCOME')
dcf.forecast_as_percent_of_revenue(type = 'BALANCE')
dcf.forecast_as_percent_of_revenue(type = 'CF')
None

In [13]:
x = dcf.style_jupyter(dcf.bal_forecast)
y = dcf.style_jupyter(dcf.inc_forecast)
display_side_by_side(x,y)
dcf.style_jupyter(dcf.cf_forecast)

,2021-09-30,2021-12-31,2022-03-31,2022-06-30,2022-09-30,T+1,T+2,T+3,T+4,T+5
assetsc,"$59,889.0","$60,979.0","$60,424.0","$63,847.0","$65,236.0","$62,899.6","$64,472.09","$66,083.89","$67,735.99","$69,429.39"
assetsnc,"$119,339.0","$121,039.0","$117,931.0","$113,877.0","$109,888.0","$118,998.14","$121,973.09","$125,022.42","$128,147.98","$131,351.68"
receivables,"$14,911.0","$15,283.0","$15,594.0","$16,139.0","$15,890.0","$16,232.89","$16,638.72","$17,054.68","$17,481.05","$17,918.08"
inventory,"$10,387.0","$10,387.0","$10,990.0","$11,437.0","$11,675.0","$11,440.27","$11,726.27","$12,019.43","$12,319.92","$12,627.91"
assets,"$179,228.0","$182,018.0","$178,355.0","$177,724.0","$175,124.0","$180,430.37","$184,941.13","$189,564.66","$194,303.77","$199,161.37"
liabilitiesc,"$44,561.0","$45,226.0","$43,390.0","$44,821.0","$45,543.0","$45,503.53","$46,641.12","$47,807.15","$49,002.33","$50,227.38"
liabilitiesnc,"$64,395.0","$62,769.0","$60,256.0","$56,546.0","$54,982.0","$61,710.64","$63,253.41","$64,834.74","$66,455.61","$68,117.0"
payables,"$8,961.0","$11,055.0","$9,309.0","$9,765.0","$10,153.0","$9,913.7","$10,161.54","$10,415.58","$10,675.97","$10,942.87"
debt,"$33,928.0","$33,751.0","$33,148.0","$32,597.0","$32,027.0","$33,181.92","$34,011.47","$34,861.75","$35,733.3","$36,626.63"
equity,"$70,272.0","$74,023.0","$74,709.0","$76,357.0","$74,599.0","$76,463.97","$78,375.57","$80,334.96","$82,343.34","$84,401.92"
retearn,"$121,092.0","$123,060.0","$124,380.0","$126,216.0","$127,917.0","$128,138.01","$131,341.46","$134,625.0","$137,990.62","$141,440.39"
revenue,"$23,338.0","$24,804.0","$23,426.0","$24,020.0","$23,791.0","$24,385.78","$24,995.42","$25,620.3","$26,260.81","$26,917.33"
depamor,"$1,814.0","$1,843.0","$1,769.0","$1,744.0","$1,685.0","$1,811.92","$1,857.22","$1,903.65","$1,951.24","$2,000.03"
intexp,$20.0,$60.0,$10.0,$38.0,$51.0,$38.58,$39.54,$40.53,$41.54,$42.58
taxrate,$0.0,$0.0,$0.0,$0.0,$0.0,$0.0,$0.0,$0.0,$0.0,$0.0
,2021-09-30,2021-12-31,2022-03-31,2022-06-30,2022-09-30,T+1,T+2,T+3,T+4,T+5
revenue,"$23,338.0","$24,804.0","$23,426.0","$24,020.0","$23,791.0","$24,385.78","$24,995.42","$25,620.3","$26,260.81","$26,917.33"
cogs,"$7,250.0","$7,955.0","$7,598.0","$7,919.0","$7,807.0","$7,909.29","$8,107.03","$8,309.7","$8,517.44","$8,730.38"
gp,"$16,088.0","$16,849.0","$15,828.0","$16,101.0","$15,984.0","$16,476.48","$16,888.39","$17,310.6","$17,743.37","$18,186.95"
opex,"$10,382.0","$11,957.0","$10,080.0","$10,014.0","$9,768.0","$10,492.98","$10,755.31","$11,024.19","$11,299.79","$11,582.29"
opinc,"$5,706.0","$4,892.0","$5,748.0","$6,087.0","$6,216.0","$5,983.5","$6,133.09","$6,286.41","$6,443.57","$6,604.66"
ebt,"$3,849.0","$4,836.0","$5,862.0","$5,840.0","$5,822.0","$5,928.93","$6,077.15","$6,229.08","$6,384.81","$6,544.43"
netinc,"$3,667.0","$4,736.0","$5,149.0","$4,814.0","$4,458.0","$4,656.15","$4,772.55","$4,891.86","$5,014.16","$5,139.51"
ebitda,"$5,683.0","$6,739.0","$7,641.0","$7,622.0","$7,558.0","$7,738.07","$7,931.52","$8,129.81","$8,333.05","$8,541.38"
depamor,"$1,814.0","$1,843.0","$1,769.0","$1,744.0","$1,685.0","$1,811.92","$1,857.22","$1,903.65","$1,951.24","$2,000.03"

In [14]:
dcf.forecast_cf_from_opperations()
dcf.discount(ERM = 0.04, RFR = 0)
dcf.terminal_value(TERMINAL_GROWTH=0.05)
dcf.estimate_price_per_share()

[*********************100%***********************]  2 of 2 completed
beta:  1.0099814373563925
wacc:  0.028522842502073313
npv:  23785728680.80639
terminal value:  173923267958.33224
pv future cash flows:  75.19797219472449

## Bull

In [15]:
dcf = DCF(ticker=ticker, REV_GROWTH=0.06)
dcf.forecast_as_percent_of_revenue(type = 'INCOME')
dcf.forecast_as_percent_of_revenue(type = 'BALANCE')
dcf.forecast_as_percent_of_revenue(type = 'CF')
dcf.forecast_cf_from_opperations()
dcf.discount(ERM = 0.04, RFR = 0)
dcf.terminal_value(TERMINAL_GROWTH=0.06)
dcf.estimate_price_per_share()

[*********************100%***********************]  2 of 2 completed
beta:  1.0099821744968336
wacc:  0.02858663849784341
npv:  26326700560.82226
terminal value:  207160150810.41028
pv future cash flows:  88.80596257991412

# Bear

In [16]:
dcf = DCF(ticker=ticker, REV_GROWTH=0.01)
dcf.forecast_as_percent_of_revenue(type = 'INCOME')
dcf.forecast_as_percent_of_revenue(type = 'BALANCE')
dcf.forecast_as_percent_of_revenue(type = 'CF')
dcf.forecast_cf_from_opperations()
dcf.discount(ERM = 0.04, RFR = 0)
dcf.terminal_value(TERMINAL_GROWTH=0.02)
dcf.estimate_price_per_share()

[*********************100%***********************]  2 of 2 completed
beta:  1.0099813181256359
wacc:  0.028498037292828328
npv:  22765011029.38586
terminal value:  157099879406.16724
pv future cash flows:  68.41102458512185